---
topdir: ~/.offlineimap-mozilla
delete:
    3:
        - Bugs IT
        - Bugs Resolved
        - Trash
        - Junk
        - Cron
        - Infra-All
        - Nagios
        - Preproduction
        - Puppet
        - Staging
    7:
        - Bug requests
        - Bugs Releng
        - Bugs Unsorted
        - buildbot-devel
